### ISSUE TITLE
Trouble randomizing WC2011

### ISSUE THREAD

**Issue by UnknownDarkness** [mSpoeth/YgoNdsRandomizer#2]
Hello, hope someone still works here...

Trying to run the most recent Jar file, it results in a file, however DesMuMe refuses to run it, saying that it can't write data and to restart the game after reinserting the game. 
I was unable to find a specific settings that causes this, it seems to be a critical error. 
On my side, do I need a specific region? Are there filename restrictions? The Readme doesn't say anything about it...

**Comment by kathanaddaeus** [comment]
Hmm, that's strange. While I usually use melonDS to emulate NDS, I just tried with Desmume and it worked there too. Could you elaborate which game you tried to randomize? I have both the EU and USA versions of WCS 09 - 11 on me and all of them worked. There shouldn't be any restrictions, neither on the name, nor the region, but I never tried a japanese rom, I suppose.

**Comment by UnknownDarkness** [comment]
I tried EU and USA Versions of 2011. 
Did you build from source or did you use the release file in the releases? 
Is there something that would require a specific minimum version of Java or Windows (Windows 7 64x here, for the record, and Java  8)? Some place the Rom or the randomizer may or may not be allowed to be (Placed them in a folder in my Downloads folder and another time in a Folder on my Desktop)? 
The resulting rom, btw, is 5MB smaller than the original rom. (123 vs 128). While I can't say for certain, this would imply to me that some error is happening on my end. Is there some way to run the Jar, specifically, as a Admin? 
Tried building it myself, but I struggle getting gradle to work.

**Comment by kathanaddaeus** [comment]
Your OS shouldn't matter, as your installed Java version handles that stuff. The app's built for Java 8 too, as it's the most commonly installed version. I only tested the latest Github release myself, so that shouldn't be a problem either. I'm no expert with desmume, but I succesfully launched normal and randomized YGO roms from any folder without a problem (Downloads, Desktop and from my backup drive). Could you try to run the rom with another emulator to check? [melonDS](https://melonds.kuribo64.net/) and Desmume both worked. Because you manage to see the UI and get to the rom saving dialoge, I doubt there's a problem with the way you run the app.

I don't doubt much will go wrong, but just to be sure, to reproduce my steps with desmume:
(I use the newest build of desmume from their website)
- Run the randomizer, select my rom, select desired settings
- Click save, after a short moment a dialogue opens and I save the new rom to my drive (named "random")
- I run desmume, File -> "Select rom" (Ctrl + o) and start random.nds  

I managed to get to the start screen every time this way

Altough I doubt it happens, since you manage to save the rom and it has the correct file size, but you could try to run the app from CMD and if any exceptions are thrown, you'd be able to see them printed there.

Side note: The 5 fewer MB are the same for me, I'm not too sure, since I haven't worked on those NDS roms for a good while, but if I remember correctly, there's a whole lot of empty space at the end of some file reference files and the tool to dissect and restitch everything together cleans that up

**Comment by UnknownDarkness** [comment]
MelonDS appears to work, for some reason, I guess. 

What version of Desmume do you use? Greater than 0.9.11? Might be worth it to add a disclaimer to that end in the Readme, as Desmume 0.9.11 doesn't.

Sorry to bother you with trivialities. It works now.

**Comment by kathanaddaeus** [comment]
I've found an older desmume install on my drive that works too, which was 0.9.11 exactly. Don't think I need to add it to the readme just yet, maybe I will, if more people have similar problems. 

I'm going to mark this issue as resolved, since it works on your end now. Feel free to open another if anything catches your eye.
Hope you'll enjoy 2011 randomized!
